// <auto-generated />
using System;
using CampusConnect.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251027063220_Seeds")]
    partial class Seeds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusConnect.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Instructor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentsEnrolled")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = 1,
                            Code = "COMP 232",
                            Instructor = "Dr. Li",
                            StudentsEnrolled = 0,
                            Title = "Mathematics for Computer Science"
                        },
                        new
                        {
                            CourseId = 2,
                            Code = "COMP 248",
                            Instructor = "Prof. Smith",
                            StudentsEnrolled = 0,
                            Title = "Object-Oriented Programming I"
                        },
                        new
                        {
                            CourseId = 3,
                            Code = "COMP 249",
                            Instructor = "Prof. Miller",
                            StudentsEnrolled = 0,
                            Title = "Object-Oriented Programming II"
                        },
                        new
                        {
                            CourseId = 4,
                            Code = "COMP 335",
                            Instructor = "Dr. Chen",
                            StudentsEnrolled = 0,
                            Title = "Introduction to Theoretical Computer Science"
                        },
                        new
                        {
                            CourseId = 5,
                            Code = "COMP 346",
                            Instructor = "Dr. Johnson",
                            StudentsEnrolled = 0,
                            Title = "Operating Systems"
                        },
                        new
                        {
                            CourseId = 6,
                            Code = "COMP 348",
                            Instructor = "Prof. White",
                            StudentsEnrolled = 0,
                            Title = "Principles of Programming Languages"
                        },
                        new
                        {
                            CourseId = 7,
                            Code = "COMP 352",
                            Instructor = "Dr. Thompson",
                            StudentsEnrolled = 0,
                            Title = "Data Structures and Algorithms"
                        },
                        new
                        {
                            CourseId = 8,
                            Code = "COMP 354",
                            Instructor = "Dr. Davis",
                            StudentsEnrolled = 0,
                            Title = "Introduction to Software Engineering"
                        },
                        new
                        {
                            CourseId = 9,
                            Code = "COMP 376",
                            Instructor = "Prof. Garcia",
                            StudentsEnrolled = 0,
                            Title = "Introduction to Game Development"
                        },
                        new
                        {
                            CourseId = 10,
                            Code = "COMP 426",
                            Instructor = "Dr. Patel",
                            StudentsEnrolled = 0,
                            Title = "Artificial Intelligence"
                        },
                        new
                        {
                            CourseId = 11,
                            Code = "COMP 472",
                            Instructor = "Dr. Ahmed",
                            StudentsEnrolled = 0,
                            Title = "Machine Learning"
                        },
                        new
                        {
                            CourseId = 12,
                            Code = "COMP 445",
                            Instructor = "Dr. Walker",
                            StudentsEnrolled = 0,
                            Title = "Data Communication and Networks"
                        },
                        new
                        {
                            CourseId = 13,
                            Code = "COMP 428",
                            Instructor = "Prof. Roberts",
                            StudentsEnrolled = 0,
                            Title = "Computer Graphics"
                        },
                        new
                        {
                            CourseId = 14,
                            Code = "COMP 465",
                            Instructor = "Dr. Evans",
                            StudentsEnrolled = 0,
                            Title = "Web Services and Applications"
                        },
                        new
                        {
                            CourseId = 15,
                            Code = "COMP 490",
                            Instructor = "Dr. Wilson",
                            StudentsEnrolled = 0,
                            Title = "Capstone Project"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int?>("Grade")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            CourseId = 1,
                            Grade = 90,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 2,
                            CourseId = 2,
                            Grade = 85,
                            StudentId = 1
                        },
                        new
                        {
                            EnrollmentId = 3,
                            CourseId = 2,
                            Grade = 88,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 4,
                            CourseId = 3,
                            Grade = 92,
                            StudentId = 2
                        },
                        new
                        {
                            EnrollmentId = 5,
                            CourseId = 1,
                            Grade = 95,
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 6,
                            CourseId = 3,
                            Grade = 89,
                            StudentId = 3
                        },
                        new
                        {
                            EnrollmentId = 7,
                            CourseId = 4,
                            Grade = 80,
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 8,
                            CourseId = 5,
                            Grade = 84,
                            StudentId = 4
                        },
                        new
                        {
                            EnrollmentId = 9,
                            CourseId = 1,
                            Grade = 91,
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 10,
                            CourseId = 6,
                            Grade = 87,
                            StudentId = 5
                        },
                        new
                        {
                            EnrollmentId = 11,
                            CourseId = 7,
                            Grade = 82,
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 12,
                            CourseId = 8,
                            Grade = 79,
                            StudentId = 6
                        },
                        new
                        {
                            EnrollmentId = 13,
                            CourseId = 2,
                            Grade = 94,
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 14,
                            CourseId = 4,
                            Grade = 88,
                            StudentId = 7
                        },
                        new
                        {
                            EnrollmentId = 15,
                            CourseId = 5,
                            Grade = 85,
                            StudentId = 8
                        },
                        new
                        {
                            EnrollmentId = 16,
                            CourseId = 6,
                            Grade = 90,
                            StudentId = 8
                        },
                        new
                        {
                            EnrollmentId = 17,
                            CourseId = 3,
                            Grade = 87,
                            StudentId = 9
                        },
                        new
                        {
                            EnrollmentId = 18,
                            CourseId = 7,
                            Grade = 82,
                            StudentId = 9
                        },
                        new
                        {
                            EnrollmentId = 19,
                            CourseId = 8,
                            Grade = 86,
                            StudentId = 10
                        },
                        new
                        {
                            EnrollmentId = 20,
                            CourseId = 9,
                            Grade = 90,
                            StudentId = 10
                        },
                        new
                        {
                            EnrollmentId = 21,
                            CourseId = 1,
                            Grade = 88,
                            StudentId = 11
                        },
                        new
                        {
                            EnrollmentId = 22,
                            CourseId = 2,
                            Grade = 91,
                            StudentId = 11
                        },
                        new
                        {
                            EnrollmentId = 23,
                            CourseId = 3,
                            Grade = 85,
                            StudentId = 12
                        },
                        new
                        {
                            EnrollmentId = 24,
                            CourseId = 4,
                            Grade = 87,
                            StudentId = 12
                        },
                        new
                        {
                            EnrollmentId = 25,
                            CourseId = 5,
                            Grade = 90,
                            StudentId = 13
                        },
                        new
                        {
                            EnrollmentId = 26,
                            CourseId = 6,
                            Grade = 92,
                            StudentId = 13
                        },
                        new
                        {
                            EnrollmentId = 27,
                            CourseId = 7,
                            Grade = 83,
                            StudentId = 14
                        },
                        new
                        {
                            EnrollmentId = 28,
                            CourseId = 8,
                            Grade = 81,
                            StudentId = 14
                        },
                        new
                        {
                            EnrollmentId = 29,
                            CourseId = 9,
                            Grade = 88,
                            StudentId = 15
                        },
                        new
                        {
                            EnrollmentId = 30,
                            CourseId = 10,
                            Grade = 84,
                            StudentId = 15
                        },
                        new
                        {
                            EnrollmentId = 31,
                            CourseId = 11,
                            Grade = 86,
                            StudentId = 16
                        },
                        new
                        {
                            EnrollmentId = 32,
                            CourseId = 12,
                            Grade = 82,
                            StudentId = 16
                        },
                        new
                        {
                            EnrollmentId = 33,
                            CourseId = 13,
                            Grade = 91,
                            StudentId = 17
                        },
                        new
                        {
                            EnrollmentId = 34,
                            CourseId = 14,
                            Grade = 89,
                            StudentId = 17
                        },
                        new
                        {
                            EnrollmentId = 35,
                            CourseId = 15,
                            Grade = 87,
                            StudentId = 18
                        },
                        new
                        {
                            EnrollmentId = 36,
                            CourseId = 1,
                            Grade = 85,
                            StudentId = 18
                        },
                        new
                        {
                            EnrollmentId = 37,
                            CourseId = 2,
                            Grade = 90,
                            StudentId = 19
                        },
                        new
                        {
                            EnrollmentId = 38,
                            CourseId = 3,
                            Grade = 88,
                            StudentId = 19
                        },
                        new
                        {
                            EnrollmentId = 39,
                            CourseId = 4,
                            Grade = 92,
                            StudentId = 20
                        },
                        new
                        {
                            EnrollmentId = 40,
                            CourseId = 5,
                            Grade = 89,
                            StudentId = 20
                        },
                        new
                        {
                            EnrollmentId = 41,
                            CourseId = 6,
                            Grade = 84,
                            StudentId = 21
                        },
                        new
                        {
                            EnrollmentId = 42,
                            CourseId = 7,
                            Grade = 86,
                            StudentId = 21
                        },
                        new
                        {
                            EnrollmentId = 43,
                            CourseId = 8,
                            Grade = 83,
                            StudentId = 22
                        },
                        new
                        {
                            EnrollmentId = 44,
                            CourseId = 9,
                            Grade = 81,
                            StudentId = 22
                        },
                        new
                        {
                            EnrollmentId = 45,
                            CourseId = 10,
                            Grade = 88,
                            StudentId = 23
                        },
                        new
                        {
                            EnrollmentId = 46,
                            CourseId = 11,
                            Grade = 90,
                            StudentId = 23
                        },
                        new
                        {
                            EnrollmentId = 47,
                            CourseId = 12,
                            Grade = 85,
                            StudentId = 24
                        },
                        new
                        {
                            EnrollmentId = 48,
                            CourseId = 13,
                            Grade = 87,
                            StudentId = 24
                        },
                        new
                        {
                            EnrollmentId = 49,
                            CourseId = 14,
                            Grade = 91,
                            StudentId = 25
                        },
                        new
                        {
                            EnrollmentId = 50,
                            CourseId = 15,
                            Grade = 89,
                            StudentId = 25
                        },
                        new
                        {
                            EnrollmentId = 51,
                            CourseId = 1,
                            Grade = 83,
                            StudentId = 26
                        },
                        new
                        {
                            EnrollmentId = 52,
                            CourseId = 2,
                            Grade = 85,
                            StudentId = 26
                        },
                        new
                        {
                            EnrollmentId = 53,
                            CourseId = 3,
                            Grade = 88,
                            StudentId = 27
                        },
                        new
                        {
                            EnrollmentId = 54,
                            CourseId = 4,
                            Grade = 90,
                            StudentId = 27
                        },
                        new
                        {
                            EnrollmentId = 55,
                            CourseId = 5,
                            Grade = 84,
                            StudentId = 28
                        },
                        new
                        {
                            EnrollmentId = 56,
                            CourseId = 6,
                            Grade = 82,
                            StudentId = 28
                        },
                        new
                        {
                            EnrollmentId = 57,
                            CourseId = 7,
                            Grade = 87,
                            StudentId = 29
                        },
                        new
                        {
                            EnrollmentId = 58,
                            CourseId = 8,
                            Grade = 85,
                            StudentId = 29
                        },
                        new
                        {
                            EnrollmentId = 59,
                            CourseId = 9,
                            Grade = 89,
                            StudentId = 30
                        },
                        new
                        {
                            EnrollmentId = 60,
                            CourseId = 10,
                            Grade = 90,
                            StudentId = 30
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("GPA")
                        .HasColumnType("float");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            GPA = 3.7999999999999998,
                            LastName = "Smith",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            GPA = 3.5,
                            LastName = "Johnson",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "charlie.williams@example.com",
                            FirstName = "Charlie",
                            GPA = 3.8999999999999999,
                            LastName = "Williams",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "david.jones@example.com",
                            FirstName = "David",
                            GPA = 3.6000000000000001,
                            LastName = "Jones",
                            Program = "Information Systems Security"
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "eva.brown@example.com",
                            FirstName = "Eva",
                            GPA = 3.7000000000000002,
                            LastName = "Brown",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 6,
                            Email = "liam.miller@example.com",
                            FirstName = "Liam",
                            GPA = 3.3999999999999999,
                            LastName = "Miller",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 7,
                            Email = "sophia.davis@example.com",
                            FirstName = "Sophia",
                            GPA = 3.8999999999999999,
                            LastName = "Davis",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 8,
                            Email = "noah.wilson@example.com",
                            FirstName = "Noah",
                            GPA = 3.2000000000000002,
                            LastName = "Wilson",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 9,
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            GPA = 3.6000000000000001,
                            LastName = "Taylor",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 10,
                            Email = "ethan.anderson@example.com",
                            FirstName = "Ethan",
                            GPA = 3.2999999999999998,
                            LastName = "Anderson",
                            Program = "Information Systems Security"
                        },
                        new
                        {
                            StudentId = 11,
                            Email = "mia.thomas@example.com",
                            FirstName = "Mia",
                            GPA = 3.5,
                            LastName = "Thomas",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 12,
                            Email = "jacob.lee@example.com",
                            FirstName = "Jacob",
                            GPA = 3.6000000000000001,
                            LastName = "Lee",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 13,
                            Email = "isabella.white@example.com",
                            FirstName = "Isabella",
                            GPA = 3.7999999999999998,
                            LastName = "White",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 14,
                            Email = "william.harris@example.com",
                            FirstName = "William",
                            GPA = 3.3999999999999999,
                            LastName = "Harris",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 15,
                            Email = "emily.clark@example.com",
                            FirstName = "Emily",
                            GPA = 3.7000000000000002,
                            LastName = "Clark",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 16,
                            Email = "james.lewis@example.com",
                            FirstName = "James",
                            GPA = 3.2999999999999998,
                            LastName = "Lewis",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 17,
                            Email = "ava.robinson@example.com",
                            FirstName = "Ava",
                            GPA = 3.8999999999999999,
                            LastName = "Robinson",
                            Program = "Information Systems Security"
                        },
                        new
                        {
                            StudentId = 18,
                            Email = "michael.walker@example.com",
                            FirstName = "Michael",
                            GPA = 3.2000000000000002,
                            LastName = "Walker",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 19,
                            Email = "charlotte.hall@example.com",
                            FirstName = "Charlotte",
                            GPA = 3.6000000000000001,
                            LastName = "Hall",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 20,
                            Email = "alexander.allen@example.com",
                            FirstName = "Alexander",
                            GPA = 3.5,
                            LastName = "Allen",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 21,
                            Email = "ella.young@example.com",
                            FirstName = "Ella",
                            GPA = 3.7000000000000002,
                            LastName = "Young",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 22,
                            Email = "daniel.king@example.com",
                            FirstName = "Daniel",
                            GPA = 3.3999999999999999,
                            LastName = "King",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 23,
                            Email = "amelia.wright@example.com",
                            FirstName = "Amelia",
                            GPA = 3.8999999999999999,
                            LastName = "Wright",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 24,
                            Email = "matthew.scott@example.com",
                            FirstName = "Matthew",
                            GPA = 3.2999999999999998,
                            LastName = "Scott",
                            Program = "Information Systems Security"
                        },
                        new
                        {
                            StudentId = 25,
                            Email = "harper.green@example.com",
                            FirstName = "Harper",
                            GPA = 3.6000000000000001,
                            LastName = "Green",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 26,
                            Email = "joseph.adams@example.com",
                            FirstName = "Joseph",
                            GPA = 3.5,
                            LastName = "Adams",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 27,
                            Email = "evelyn.baker@example.com",
                            FirstName = "Evelyn",
                            GPA = 3.7999999999999998,
                            LastName = "Baker",
                            Program = "Data Science"
                        },
                        new
                        {
                            StudentId = 28,
                            Email = "samuel.gonzalez@example.com",
                            FirstName = "Samuel",
                            GPA = 3.3999999999999999,
                            LastName = "Gonzalez",
                            Program = "Computer Science"
                        },
                        new
                        {
                            StudentId = 29,
                            Email = "elizabeth.nelson@example.com",
                            FirstName = "Elizabeth",
                            GPA = 3.7000000000000002,
                            LastName = "Nelson",
                            Program = "Software Engineering"
                        },
                        new
                        {
                            StudentId = 30,
                            Email = "david.carter@example.com",
                            FirstName = "David",
                            GPA = 3.2999999999999998,
                            LastName = "Carter",
                            Program = "Data Science"
                        });
                });

            modelBuilder.Entity("CampusConnect.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CampusConnect.Models.Enrollment", b =>
                {
                    b.HasOne("CampusConnect.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CampusConnect.Models.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("CampusConnect.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
